version: '3'
services:
  webnodb:
    container_name: webnodb
    image: webnodb
    build:
      context: .
      dockerfile: webnodb/Dockerfile
    ports:
      - "8000:5000"
    links:
      - "mongodb:database"
    depends_on:
      - mongodb
  webdb:
    container_name: webdb
    image: webdb
    environment:
      - MONGO_ADMIN=fisa
      - MONGO_ADMIN_PASSWORD=fisa
      - MONGO_HOSTNAME=mongodb
      - MONGO_PORT=27017
    links:
      - "mongodb:database"
    build:
      context: .
      dockerfile: webdb/Dockerfile
    ports:
      - "8001:5000"
    depends_on:
      - mongodb
  mongodb: 
    container_name: mongodb
    image: mongodb/mongodb-community-server
    environment:
      - MONGO_INITDB_ROOT_USERNAME=fisa 
      - MONGO_INITDB_ROOT_PASSWORD=fisa
      - MONGO_INITDB_DATABASE=web
    ports: 
      - "27017:27017"
  nginx:
    container_name: nginx
    image: nginx
    ports:
      - "80:80"
    depends_on: 
      - "webdb"
      - "webnodb"
      - "mongodb"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/access.log:/var/log/nginx/access.log
